(include-all "../../value/index.lisp")
(include-all "program.lisp")
(include "check.lisp" check-program)
(include "eval.lisp" eval-program)
(include "parse.lisp" parse-program parse-exp)
(include "form.lisp" form-program)
