(include "../../value/index.lisp")

(include "type.lisp")
(include "exp.lisp")
(include "program.lisp")
(include "ctx.lisp")
(include "check.lisp")
(include "eval.lisp")
(include "parse.lisp")
(include "form.lisp")
