(let ((x (begin
           (print-int 1)
           (newline)
           (print-int 2)
           (newline)
           (print-int 3)
           (newline)
           6)))
  (begin
    (print-int 4)
    (newline)
    (print-int 5)
    (newline)
    (print-int 6)
    (newline)
    (iadd x x)))
