(include-all "value/index.lisp")
(include-all "builtin/index.lisp")
(include-all "langs/s/index.lisp")
(include-all "langs/c/index.lisp")
(include-all "langs/x86/index.lisp")
(include-all "passes/index.lisp")
(include-all "compile/index.lisp")
