name: test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with: { node-version: latest }
      - working-directory: runtime
        run: make
      - working-directory: compiler
        run: npm ci && sh scripts/test-all.sh
